import openai

from method import get_key_values_from_file


def chat(MSGS, MaxToken=3000, outputs=3):
    # We use the Chat Completion endpoint for chat like inputs
    response = openai.ChatCompletion.create(
        # model used here is ChatGPT
        # You can use all these models for this endpoint:
        # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314,
        # gpt-3.5-turbo, gpt-3.5-turbo-0301
        model="gpt-3.5-turbo",
        messages=MSGS,
        # max_tokens generated by the AI model
        # maximu value can be 4096 tokens for "gpt-3.5-turbo"
        max_tokens=MaxToken,
        # number of output variations to be generated by AI model
        n=outputs,
    )
    return response.choices[0].message


# config = get_key_values_from_file()
# Set your OpenAI API key
key = get_key_values_from_file().get('chatGPT_login_key')

openai.api_key = key
# Create a chat-based completion
MSGS = """ info about pakistan"""
chat(MSGS, MaxToken=3000, outputs=1)

a=1
